/* FÖRKORT-data — vanliga svenska militära förkortningar.
   Källa: Handbok Armé — Begrepp och förkortningar 2016 (AH Begrepp 2016).
   Urval: ~120 av de mest använda inom HV/markstrid.
   Inte fastställt av FM. Repetitions-/utbildningssyfte.
*/
window.FORKORT_DATA = {
  meta: {
    title: 'FÖRKORT',
    subtitle: 'Militära förkortningar',
    source: 'Handbok Armé — Begrepp och förkortningar 2016'
  },

  cards: [
    /* ─── Befäl & rang ─── */
    { id: 'gen', category: 'Befäl & rang', front: 'gen', back: 'general' },
    { id: 'genlt', category: 'Befäl & rang', front: 'genlt', back: 'generallöjtnant' },
    { id: 'genmj', category: 'Befäl & rang', front: 'genmj', back: 'generalmajor' },
    { id: 'briggen', category: 'Befäl & rang', front: 'briggen', back: 'brigadgeneral' },
    { id: 'mj', category: 'Befäl & rang', front: 'mj', back: 'major' },
    { id: 'kn', category: 'Befäl & rang', front: 'kn', back: 'kapten' },
    { id: 'lt', category: 'Befäl & rang', front: 'lt', back: 'löjtnant' },
    { id: 'fk', category: 'Befäl & rang', front: 'fk', back: 'fänrik' },
    { id: 'fv', category: 'Befäl & rang', front: 'fv', back: 'förvaltare' },
    { id: 'regfv', category: 'Befäl & rang', front: 'regfv', back: 'regementsförvaltare' },
    { id: 'fj', category: 'Befäl & rang', front: 'fj', back: 'fanjunkare' },
    { id: 'serg', category: 'Befäl & rang', front: 'serg', back: 'sergeant' },
    { id: 'krp', category: 'Befäl & rang', front: 'krp', back: 'korpral' },
    { id: 'men', category: 'Befäl & rang', front: 'men', back: 'menig' },
    { id: 'bef', category: 'Befäl & rang', front: 'bef', back: 'befäl / befälhavare' },
    { id: 'ch', category: 'Befäl & rang', front: 'ch', back: 'chef' },
    { id: 'C', category: 'Befäl & rang', front: 'C', back: 'chefen för\n(t.ex. C PROD = Chef Produktion)' },
    { id: 'kdt', category: 'Befäl & rang', front: 'kdt', back: 'kommendant' },
    { id: 'kvm', category: 'Befäl & rang', front: 'kvm', back: 'kvartermästare' },
    { id: 'duc', category: 'Befäl & rang', front: 'duc', back: 'direkt underställd(a) chef(er)' },

    /* ─── Förband & truppslag ─── */
    { id: 'inf', category: 'Förband & truppslag', front: 'inf', back: 'infanteri' },
    { id: 'kav', category: 'Förband & truppslag', front: 'kav', back: 'kavalleri' },
    { id: 'art', category: 'Förband & truppslag', front: 'art', back: 'artilleri' },
    { id: 'ing', category: 'Förband & truppslag', front: 'ing', back: 'ingenjör' },
    { id: 'pv', category: 'Förband & truppslag', front: 'pv', back: 'pansarvärn' },
    { id: 'fskj', category: 'Förband & truppslag', front: 'fskj', back: 'fallskärmsjägare' },
    { id: 'fbasj', category: 'Förband & truppslag', front: 'fbasj', back: 'flygbasjägare' },
    { id: 'kj', category: 'Förband & truppslag', front: 'kj', back: 'kustjägare' },
    { id: 'amf', category: 'Förband & truppslag', front: 'amf', back: 'amfibie' },
    { id: 'hv', category: 'Förband & truppslag', front: 'hv', back: 'hemvärn' },
    { id: 'mek', category: 'Förband & truppslag', front: 'mek', back: 'mekaniserad / mekanisk' },
    { id: 'mekbat', category: 'Förband & truppslag', front: 'mekbat', back: 'mekaniserad bataljon' },
    { id: 'mekB', category: 'Förband & truppslag', front: 'mekB', back: 'mekaniserad brigad' },
    { id: 'brig', category: 'Förband & truppslag', front: 'brig', back: 'brigad' },
    { id: 'bat', category: 'Förband & truppslag', front: 'bat', back: 'bataljon' },
    { id: 'reg', category: 'Förband & truppslag', front: 'reg', back: 'regemente' },
    { id: 'komp', category: 'Förband & truppslag', front: 'komp', back: 'kompani' },
    { id: 'plut', category: 'Förband & truppslag', front: 'plut', back: 'pluton' },
    { id: 'grp', category: 'Förband & truppslag', front: 'grp', back: 'grupp / gruppering' },
    { id: 'fi', category: 'Förband & truppslag', front: 'fi', back: 'fiende / fientlig' },

    /* ─── Vapen & ammunition ─── */
    { id: 'ak', category: 'Vapen & ammunition', front: 'ak', back: 'automatkarbin' },
    { id: 'ag', category: 'Vapen & ammunition', front: 'ag', back: 'automatgevär' },
    { id: 'akan', category: 'Vapen & ammunition', front: 'akan', back: 'automatkanon' },
    { id: 'ksp', category: 'Vapen & ammunition', front: 'ksp', back: 'kulspruta' },
    { id: 'kpist', category: 'Vapen & ammunition', front: 'kpist', back: 'kulsprutepistol' },
    { id: 'pist', category: 'Vapen & ammunition', front: 'pist', back: 'pistol' },
    { id: 'g', category: 'Vapen & ammunition', front: 'g', back: 'gevär' },
    { id: 'psg', category: 'Vapen & ammunition', front: 'psg', back: 'prickskyttegevär' },
    { id: 'kan', category: 'Vapen & ammunition', front: 'kan', back: 'kanon' },
    { id: 'haub', category: 'Vapen & ammunition', front: 'haub', back: 'haubits' },
    { id: 'grk', category: 'Vapen & ammunition', front: 'grk', back: 'granatkastare' },
    { id: 'grg', category: 'Vapen & ammunition', front: 'grg', back: 'granatgevär' },
    { id: 'grspr', category: 'Vapen & ammunition', front: 'grspr', back: 'granatspruta' },
    { id: 'hgr', category: 'Vapen & ammunition', front: 'hgr', back: 'handgranat' },
    { id: 'gr', category: 'Vapen & ammunition', front: 'gr', back: 'granat' },
    { id: 'rb', category: 'Vapen & ammunition', front: 'rb', back: 'robot' },
    { id: 'pvrb', category: 'Vapen & ammunition', front: 'pvrb', back: 'pansarvärnsrobot' },
    { id: 'lvrb', category: 'Vapen & ammunition', front: 'lvrb', back: 'luftvärnsrobot' },
    { id: 'rak', category: 'Vapen & ammunition', front: 'rak', back: 'raket' },
    { id: 'rg', category: 'Vapen & ammunition', front: 'rg', back: 'raketgevär' },
    { id: 'am', category: 'Vapen & ammunition', front: 'am', back: 'ammunition' },
    { id: 'ptr', category: 'Vapen & ammunition', front: 'ptr', back: 'patron' },
    { id: 'prj', category: 'Vapen & ammunition', front: 'prj', back: 'projektil' },

    /* ─── Fordon & transport ─── */
    { id: 'bv', category: 'Fordon & transport', front: 'bv', back: 'bandvagn' },
    { id: 'pbv', category: 'Fordon & transport', front: 'pbv', back: 'pansarbandvagn' },
    { id: 'pskfo', category: 'Fordon & transport', front: 'pskfo', back: 'pansarskyttefordon' },
    { id: 'pfo', category: 'Fordon & transport', front: 'pfo', back: 'pansarfordon' },
    { id: 'lb', category: 'Fordon & transport', front: 'lb', back: 'lastbil' },
    { id: 'ltgb', category: 'Fordon & transport', front: 'ltgb', back: 'lastterrängbil' },
    { id: 'ptgb', category: 'Fordon & transport', front: 'ptgb', back: 'personterrängbil' },
    { id: 'pb', category: 'Fordon & transport', front: 'pb', back: 'personbil' },
    { id: 'mc', category: 'Fordon & transport', front: 'mc', back: 'motorcykel' },
    { id: 'mb', category: 'Fordon & transport', front: 'mb', back: 'motorbåt' },
    { id: 'ptrb', category: 'Fordon & transport', front: 'ptrb', back: 'patrullbåt' },
    { id: 'fpl', category: 'Fordon & transport', front: 'fpl', back: 'flygplan' },
    { id: 'hkp', category: 'Fordon & transport', front: 'hkp', back: 'helikopter' },
    { id: 'ahkp', category: 'Fordon & transport', front: 'ahkp', back: 'attackhelikopter' },
    { id: 'fo', category: 'Fordon & transport', front: 'fo', back: 'fordon' },
    { id: 'foch', category: 'Fordon & transport', front: 'foch', back: 'fordonschef' },
    { id: 'jvg', category: 'Fordon & transport', front: 'jvg', back: 'järnväg' },
    { id: 'drivm', category: 'Fordon & transport', front: 'drivm', back: 'drivmedel' },

    /* ─── Ledning & rapportering ─── */
    { id: 'hkv', category: 'Ledning & rapportering', front: 'hkv', back: 'högkvarteret' },
    { id: 'lpl', category: 'Ledning & rapportering', front: 'lpl', back: 'ledningsplats' },
    { id: 'flp', category: 'Ledning & rapportering', front: 'flp', back: 'främre ledningsplats' },
    { id: 'fob', category: 'Ledning & rapportering', front: 'fob', back: 'framskjuten operationsbas' },
    { id: 'bis', category: 'Ledning & rapportering', front: 'bis', back: 'beslut i stort\n\n(Chefens avsikt avseende önskat slutläge / målbild, hur striden ska genomföras och med vilka syften.)' },
    { id: 'btf', category: 'Ledning & rapportering', front: 'btf', back: 'beslutstillfälle' },
    { id: 'bsp', category: 'Ledning & rapportering', front: 'bsp', back: 'beslutstödsplan' },
    { id: 'gfi', category: 'Ledning & rapportering', front: 'gfi', back: 'genomförandeidé' },
    { id: 'eo', category: 'Ledning & rapportering', front: 'eo', back: 'eldorder' },
    { id: 'ord', category: 'Ledning & rapportering', front: 'ord', back: 'ordonnans' },
    { id: 'ori', category: 'Ledning & rapportering', front: 'ori', back: 'orientering' },
    { id: 'rapp', category: 'Ledning & rapportering', front: 'rapp', back: 'rapport' },
    { id: 'rs', category: 'Ledning & rapportering', front: 'rs', back: 'rapportställe' },
    { id: 'dart', category: 'Ledning & rapportering', front: 'dart', back: 'datarapporteringsterminal' },
    { id: 'igu', category: 'Ledning & rapportering', front: 'igu', back: 'indelning, gruppering och uppgifter' },
    { id: 'roe', category: 'Ledning & rapportering', front: 'roe', back: 'rules of engagement (insatsregler)' },
    { id: 'mob', category: 'Ledning & rapportering', front: 'mob', back: 'mobilisering' },

    /* ─── Sjukvård & skydd ─── */
    { id: 'sj', category: 'Sjukvård & skydd', front: 'sj-', back: 'sjuk-' },
    { id: 'fsjh', category: 'Sjukvård & skydd', front: 'fsjh', back: 'fältsjukhus' },
    { id: 'ksjh', category: 'Sjukvård & skydd', front: 'ksjh', back: 'krigssjukhus' },
    { id: 'lak', category: 'Sjukvård & skydd', front: 'läk', back: 'läkare' },
    { id: 'amb', category: 'Sjukvård & skydd', front: 'amb', back: 'ambulans' },
    { id: 'axp', category: 'Sjukvård & skydd', front: 'axp', back: 'ambulansöverlämningsplats' },
    { id: 'isb', category: 'Sjukvård & skydd', front: 'isb', back: 'indikering, sanering och brand' },
    { id: 'cbrn', category: 'Sjukvård & skydd', front: 'cbrn', back: 'Chemical, Biological, Radiological, Nuclear\n(kemiska, biologiska, radiologiska, nukleära)' },
    { id: 'bstridsm', category: 'Sjukvård & skydd', front: 'b-stridsm', back: 'biologiska stridsmedel' },
    { id: 'cstridsm', category: 'Sjukvård & skydd', front: 'c-stridsm', back: 'kemiska stridsmedel' },

    /* ─── Samband & signalskydd ─── */
    { id: 'sb', category: 'Samband & signalskydd', front: 'sb', back: 'samband' },
    { id: 'sbpl', category: 'Samband & signalskydd', front: 'sbpl', back: 'sambandsplats' },
    { id: 'sbc', category: 'Samband & signalskydd', front: 'sbc', back: 'sambandscentral' },
    { id: 'ra', category: 'Samband & signalskydd', front: 'ra', back: 'radio' },
    { id: 'rl', category: 'Samband & signalskydd', front: 'rl', back: 'radiolänk' },
    { id: 'kv', category: 'Samband & signalskydd', front: 'kv', back: 'kortvåg' },
    { id: 'kx', category: 'Samband & signalskydd', front: 'kx', back: 'klartext' },
    { id: 'kry', category: 'Samband & signalskydd', front: 'kry', back: 'krypto' },
    { id: 'sign', category: 'Samband & signalskydd', front: 'sign', back: 'signal / signalera / signalist' },
    { id: 'SG', category: 'Samband & signalskydd', front: 'SG', back: 'signalskyddsgrad' },
    { id: 'KH', category: 'Samband & signalskydd', front: 'KH / TS', back: 'kvalificerat hemligt (Top Secret)' },
    { id: 'FTN', category: 'Samband & signalskydd', front: 'FTN', back: 'Försvarets telenät' },
    { id: 'FM', category: 'Samband & signalskydd', front: 'FM', back: 'Försvarsmakten' },
    { id: 'frekv', category: 'Samband & signalskydd', front: 'frekv', back: 'frekvens' },

    /* ─── Stridsmiljö & taktik ─── */
    { id: 'bek', category: 'Stridsmiljö & taktik', front: 'bek', back: 'bekämpa / bekämpning' },
    { id: 'bev', category: 'Stridsmiljö & taktik', front: 'bev', back: 'bevaka / bevakning' },
    { id: 'eled', category: 'Stridsmiljö & taktik', front: 'eled', back: 'eldledare' },
    { id: 'eobs', category: 'Stridsmiljö & taktik', front: 'eobs', back: 'eldobservatör' },
    { id: 'eber', category: 'Stridsmiljö & taktik', front: 'eber', back: 'eldberedskap' },
    { id: 'eti', category: 'Stridsmiljö & taktik', front: 'eti', back: 'eldtillstånd' },
    { id: 'eö', category: 'Stridsmiljö & taktik', front: 'eö', back: 'eldöverfall' },
    { id: 'frr', category: 'Stridsmiljö & taktik', front: 'frr', back: 'framryckning' },
    { id: 'rek', category: 'Stridsmiljö & taktik', front: 'rek', back: 'rekognosera / rekognosering' },
    { id: 'brytp', category: 'Stridsmiljö & taktik', front: 'brytp', back: 'brytpunkt' },
    { id: 'kp', category: 'Stridsmiljö & taktik', front: 'kp', back: 'kolonnbildningspunkt' },
    { id: 'KP-knut', category: 'Stridsmiljö & taktik', front: 'KP', back: 'knutpunkt' },
    { id: 'mnaste', category: 'Stridsmiljö & taktik', front: 'mnäste', back: 'motståndsnäste' },
    { id: 'mins', category: 'Stridsmiljö & taktik', front: 'mins', back: 'minspaning' },
    { id: 'rsv', category: 'Stridsmiljö & taktik', front: 'rsv', back: 'riktad sprängverkan' },

    /* ─── Internationella & engelska ─── */
    { id: 'eod', category: 'Internationella & engelska', front: 'eod (amröj)', back: 'Explosive Ordnance Disposal\n(ammunitionsröjning)' },
    { id: 'ied', category: 'Internationella & engelska', front: 'ied', back: 'Improvised Explosive Device' },
    { id: 'gps', category: 'Internationella & engelska', front: 'gps', back: 'Geografiskt positionssystem (Global Positioning System)' },
    { id: 'HLS', category: 'Internationella & engelska', front: 'HLS', back: 'Helicopter Landing Site\n(helikopterlandningsplats)' },
    { id: 'UAV', category: 'Internationella & engelska', front: 'UAV', back: 'Unmanned Aerial Vehicle\n(obemannad flygande farkost)' },
    { id: 'TUAV', category: 'Internationella & engelska', front: 'TUAV', back: 'Taktisk UAV' },
    { id: 'SUAV', category: 'Internationella & engelska', front: 'SUAV', back: 'Stridsteknisk UAV' },
    { id: 'MP', category: 'Internationella & engelska', front: 'MP', back: 'militärpolis' },
    { id: 'MR', category: 'Internationella & engelska', front: 'MR', back: 'militärregion' },
    { id: 'HR', category: 'Internationella & engelska', front: 'HR', back: 'Human Resources (personal)' }
  ],

  exam: [
    { q: 'Vad betyder förkortningen "bv"?',
      options: ['bevakning', 'bandvagn', 'befälsväst', 'bataljonsvärn'], correct: 1 },
    { q: 'Vad betyder förkortningen "pbv"?',
      options: ['pansarbandvagn', 'patrullbat', 'pikbil', 'pluton brigad vakt'], correct: 0 },
    { q: 'Vad betyder förkortningen "ak"?',
      options: ['attackkarbin', 'automatkarbin', 'allmän krypto', 'ammunitionskärra'], correct: 1 },
    { q: 'Vad betyder förkortningen "ksp"?',
      options: ['kulsprutepistol', 'kulspruta', 'kustspaning', 'krypteringssamband'], correct: 1 },
    { q: 'Vad betyder förkortningen "kpist"?',
      options: ['kort pistol', 'kulsprutepistol', 'kompanipistol', 'kustpatrullpistol'], correct: 1 },
    { q: 'Vad betyder förkortningen "grk"?',
      options: ['gruppchef krypto', 'granatkastare', 'granatgevär', 'gripkår'], correct: 1 },
    { q: 'Vad betyder förkortningen "pv"?',
      options: ['pansarvärn', 'patrullväg', 'personalvård', 'plutonsverk'], correct: 0 },
    { q: 'Vad betyder förkortningen "pvrb"?',
      options: ['pansarvärnsrobot', 'patrullvägsrobot', 'personalvårdsrutin', 'pålitlig vapenrutin'], correct: 0 },
    { q: 'Vad betyder förkortningen "bis"?',
      options: ['bevakning i staden', 'beslut i stort', 'biståndsinsats', 'bombsäker'], correct: 1 },
    { q: 'Vad betyder förkortningen "hkv"?',
      options: ['helikoptervärn', 'högkvarteret', 'huvudkvarter värn', 'huvudkomponent'], correct: 1 },
    { q: 'Vad betyder förkortningen "lpl"?',
      options: ['lastplats', 'ledningsplats', 'läkarplats', 'logistikpluton'], correct: 1 },
    { q: 'Vad betyder förkortningen "fskj"?',
      options: ['flygskola', 'fallskärmsjägare', 'fältskydd', 'fartygsskydd'], correct: 1 },
    { q: 'Vad betyder förkortningen "kj"?',
      options: ['kärnjägare', 'kustjägare', 'kommandojägare', 'kabeljägare'], correct: 1 },
    { q: 'Vad betyder förkortningen "fbasj"?',
      options: ['fältbasjägare', 'flygbasjägare', 'fjärrbasjägare', 'försvarsbasjägare'], correct: 1 },
    { q: 'Vad betyder förkortningen "hv"?',
      options: ['huvudvärn', 'hemvärn', 'hjälpvägen', 'huvudvapen'], correct: 1 },
    { q: 'Vad betyder förkortningen "cbrn"?',
      options: ['Chef Bevakning Region Norr', 'Civil Beredskap Räddning Norden', 'Chemical Biological Radiological Nuclear', 'Centralt Brevkommando Riks-Norr'], correct: 2 },
    { q: 'Vad betyder förkortningen "eod"?',
      options: ['End of Day', 'Explosive Ordnance Disposal', 'Enhetlig Operativ Doktrin', 'Eldobservatör'], correct: 1 },
    { q: 'Vad betyder förkortningen "ied"?',
      options: ['Identifierad enhet', 'Improvised Explosive Device', 'Internationell enhetsdoktrin', 'Insatsregler för Enheter'], correct: 1 },
    { q: 'Vad betyder förkortningen "roe"?',
      options: ['Rapport om enhet', 'Rules of Engagement', 'Regemente Operation Enhet', 'Räddning och evakuering'], correct: 1 },
    { q: 'Vad betyder förkortningen "duc"?',
      options: ['datorisk underenhet', 'direkt underställd chef', 'dunk under chefens kontroll', 'dagordning under chef'], correct: 1 },
    { q: 'Vad betyder förkortningen "FTN"?',
      options: ['Försvarets telenät', 'Främre takteknisk nivå', 'Fältnätsteknik nationell', 'Federation telecom network'], correct: 0 },
    { q: 'Vad betyder förkortningen "eo"?',
      options: ['eldorder', 'eldobservatör', 'enhetsorientering', 'evakuering'], correct: 0 },
    { q: 'Vad betyder förkortningen "eled"?',
      options: ['elektronisk ledning', 'eldledare', 'elev ledare', 'enhetsledning'], correct: 1 },
    { q: 'Vad betyder förkortningen "isb"?',
      options: ['internationell stridsbas', 'indikering, sanering och brand', 'insatsstöd brigad', 'identifiering och bevakning'], correct: 1 },
    { q: 'Vad betyder förkortningen "axp"?',
      options: ['avlämningsplats', 'ambulansöverlämningsplats', 'aktiv expedition', 'anslutningsplats'], correct: 1 }
  ]
};
